version: '3.3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
    command: /bin/sh -c "yarn start"
