version: '3.3'

services:
  frontend:
    env_file: .env
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        YARN_PARAMS: start
    volumes:
      - '.:/frontend/'
    ports:
      - 3000:3000
