version: '3.3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        YARN_PARAMS: start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
